Update proton_run.yaml

diff --git a/.github/workflows/proton_run.yaml b/.github/workflows/proton_run.yaml
--- a/.github/workflows/proton_run.yaml
+++ b/.github/workflows/proton_run.yaml
@@ -42,7 +42,14 @@ jobs:
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v2
-     
+
+    - name: Verify env_config updated
+      run: |
+        if grep -q REPLACE_ME env_config.json; then
+          echo "You must update env_config.json or update this workflow to not require it."
+          exit 1
+        fi
+      
     - name: Get changed files
       id: files
       uses: jitterbit/get-changed-files@v1
@@ -61,7 +68,8 @@ jobs:
             echo "setting found to true"
             found=true
             echo "setting outputs"
-            echo "::setOutput name=deployment-metadata-path::$changed_file"
+            echo "deployment-metadata-path=$changed_file" >> $GITHUB_OUTPUT
+
           fi
         done
         if [[ "$found" == false ]]; then
@@ -73,18 +81,18 @@ jobs:
       id: get-data
       run: |
         modified_resource_arn=$(jq -r '(.resourceMetadata.arn // .componentMetadata.arn)' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::setOutput name=resource_arn::$modified_resource_arn"
+        echo "resource_arn=$modified_resource_arn" >> $GITHUB_OUTPUT
         
         IFS=':'
         read -a split_arn <<< "$modified_resource_arn"
         proton_region=${split_arn[3]}
-        echo "::setOutput name=proton_region::$proton_region"
+        echo "proton_region=$proton_region" >> $GITHUB_OUTPUT
 
         deployment_id=$(jq -r '.deploymentId' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::setOutput name=deployment_id::$deployment_id"
+        echo "deployment_id=$deployment_id" >> $GITHUB_OUTPUT
 
         is_deleted=$(jq -r '.isResourceDeleted' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::setOutput name=is_deleted::$is_deleted"
+        echo "is_deleted=$is_deleted" >> $GITHUB_OUTPUT
 
 
         if [[ "$modified_resource_arn" == *":environment/"* ]]; then
@@ -121,13 +129,28 @@ jobs:
           component_name=${split_resources[1]}
           working_directory=$environment_name/$component_name/  
         fi
+
+        if [[ $(jq -r --arg env $environment_name 'has($env)' env_config.json) = "true" ]]; then
+          role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
+          target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
+          state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)   
+        else     
+          if [[ $(jq -r --arg env $environment_name 'has("*")' env_config.json) = "true" ]]; then
+            role_arn=$(jq -r --arg env $environment_name '.["*"]["role"]' env_config.json)
+            target_region=$(jq -r --arg env $environment_name '.["*"]["region"]' env_config.json)
+            state_bucket=$(jq -r --arg env $environment_name '.["*"]["state_bucket"]' env_config.json)
+          else
+            echo "Missing $environment_name or * from env_config.json, exiting"
+            exit 1
+          fi
+        fi
         
-        echo "::setOutput name=working_directory::$working_directory"
-        echo "::setOutput name=environment::$environment_name"
+        echo "working_directory=$working_directory" >> $GITHUB_OUTPUT
+        echo "environment=$environment_name" >> $GITHUB_OUTPUT
         
-        echo "::setOutput name=role_arn::$role_arn"
-        echo "::setOutput name=target_region::$target_region"
-        echo "::setOutput name=state_bucket::$state_bucket"
+        echo "role_arn=$role_arn" >> $GITHUB_OUTPUT
+        echo "target_region=$target_region" >> $GITHUB_OUTPUT
+        echo "state_bucket=$state_bucket" >> $GITHUB_OUTPUT
 
   terraform:
     name: 'Terraform'
@@ -198,7 +221,7 @@ jobs:
     # If this completes, then the entire workflow has successfully completed
     - name: Mark Success
       id: mark_success
-      run: echo "::setOutput name=success::True"
+      run: echo "success=True" >> $GITHUB_OUTPUT
 
   notify-proton:
     name: 'Notify Proton'
